### ISSUE TITLE
Publish on Terraform Registry (and tag version)

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/terraform-aws-codecommit-sqs#2]

**Comment by phuonghuynh** [comment]
@ronaldtse I getting unknown repo error for this;

<img width="672" alt="screenshot at dec 28 12-58-13" src="https://user-images.githubusercontent.com/705510/50504447-4c244000-0aa0-11e9-892b-ddcf4af17d15.png">

**Comment by ronaldtse** [comment]
Maybe because it's already published? Strange.

https://registry.terraform.io/modules/riboseinc/codecommit-sqs/aws/1.1.1
